version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "aws-samples/gfs-proserve-emea"
    assignees:
      - "aws-samples/gfs-proserve-emea"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group related updates together
    groups:
      python-dependencies:
        patterns:
          - "*"
    # Allow both direct and indirect dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "aws-samples/gfs-proserve-emea"
    assignees:
      - "aws-samples/gfs-proserve-emea"
    commit-message:
      prefix: "ci"
      include: "scope"
