name: terraform-checks
permissions:
  contents: read
on:
  push:
    branches:
      - terraform-module
  pull_request:
    branches:
      - terraform-module
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install checkov
      - name: CheckOv checks
        run: |
          checkov -d .
